parameters:
  runtimeId: ''

steps:

# Clean
- checkout: self
  clean: true

# Build agent layout
- script: format('dev.cmd layout Release {0}', parameters.runtimeId)
  workingDirectory: src
  displayName: Build & Layout Release

# Run test
- script: format('dev.cmd test {0}', parameters.runtimeId)
  workingDirectory: src
  displayName: Test

# Publish test results
- task: PublishTestResults@2
  displayName: Publish Test Results **/*.trx
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Agent Tests'
